### ISSUE TITLE
Ability to override functions like __le__ and __ne__.

### ISSUE THREAD

**Issue by cooljoseph1** [battlecode/battlehack20#132] opened 2020-04-24 16:42 UTC
This code gives a guaranteed win:
```python
class int2(int):
    def __ne__(self, val):
        return False
        
def turn():
    board_size = get_board_size()
    team = get_team()
    robottype = get_type()
    if robottype == RobotType.OVERLORD:
        if team == Team.BLACK:
            index = 0
        else:
            index = board_size - 1

        for i in range(board_size):
            i = int2(i)
            index = int2(index)
            row, col = index, i
            if not check_space(index, i):
                spawn(index, i)
                return
```

How it works is the following:
We make a subclass of `int` called `int2`.  We override `__ne__` so that it is not not equal to anything.  We then can place pawns anywhere on the board we want because the engine only checks that we are not placing pawns somewhere other than the back row.  Because we overrided `__ne__`, this check returns false and we can place anywhere we want on the board.

![image](https://user-images.githubusercontent.com/35083766/80236194-0afe5a80-8618-11ea-8409-0f38c52abbc0.png)

**Comment by jay20162016** [comment] 2020-04-24 16:43
Duplicate of Issue #121

**Comment by arvid220u** [comment] 2020-04-24 16:44
i really like this!! it’s a very clever hack. but yeah, duplicate of #121

**Comment by jay20162016** [comment] 2020-04-24 16:44
And the RestrictedPython is supposed to prevent that, but it doesn't work on some functions

**Closed by arvid220u** 2020-04-24 16:44 UTC
